# **Logistic Regression** Michael Julian Peter

***1. Import library***

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LogisticRegression, SGDRegressor, SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import neighbors
from sklearn.metrics import confusion_matrix, classification_report, precision_score, log_loss
from sklearn.model_selection import train_test_split, cross_val_score, KFold

import statsmodels.api as sm
import statsmodels.formula.api as smf

import matplotlib.pyplot as plt
import seaborn as sns

*2. Import dan load dataset breast cancer*

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
data = load_breast_cancer()
df = pd.DataFrame(np.c_[data['data'], data['target']], columns = np.append(data['feature_names'], ['target']))
df.head()

mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890     0.0
1        20.57         17.77  ...                  0.08902     0.0
2        19.69         21.25  ...                  0.08758     0.0
3        11.42         20.38  ...                  0.17300     0.0
4        20.29         14.34  ...                  0.07678     0.0

[5 rows x 31 columns]

***3. Membagi data menjadi X dan Y***

In [ ]:
X = data.data
Y = data.target

***4. Membagi dataset menjadi 5 bagian untuk di training dan test***

In [ ]:
kfold = KFold(n_splits=5, random_state=None, shuffle=False)

***5. Training dataset***

In [ ]:
#menggunakan solver saga
log_rgr = LogisticRegression(penalty='l2', C=100, solver='sag', max_iter = 100, class_weight='balanced')

for train_index, test_index in kfold.split(X,Y):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], Y[train_index], Y[test_index]

In [ ]:
import warnings 
warnings.filterwarnings('ignore') 

results = cross_val_score(log_rgr, X_train, y_train, cv=kfold)
print("Accuracy: ", results, '\n')

Accuracy:  [0.89130435 0.95604396 0.91208791 0.9010989  0.94505495] 



In [ ]:
log_rgr_fit = log_rgr.fit(X_train, y_train)
predictions = log_rgr_fit.predict(X_test)
predictions[1:6]

array([1, 1, 1, 0, 0])

In [ ]:
predictions_nominal = [ "M" if x < 0.5 else "B" for x in predictions]
predictions_nominal[1:6]

['B', 'B', 'B', 'M', 'M']

In [ ]:
cfm = confusion_matrix(y_test, predictions)

true_negative = cfm[0][0]
false_positive = cfm[0][1]
false_negative = cfm[1][0]
true_positive = cfm[1][1]

print('Confusion Matrix: \n', cfm, '\n')

print('True Negative:', true_negative)
print('False Positive:', false_positive)
print('False Negative:', false_negative)
print('True Positive:', true_positive)
print('Correct Predictions', 
      round((true_negative + true_positive) / len(predictions_nominal) * 100, 1), '%')

Confusion Matrix: 
 [[22  4]
 [ 7 80]] 

True Negative: 22
False Positive: 4
False Negative: 7
True Positive: 80
Correct Predictions 90.3 %


# **SGD Regressor**

In [ ]:
import warnings 
warnings.filterwarnings('ignore') 

clf = SGDClassifier(loss ='log',max_iter=50000)
clf.fit(X_train, y_train)
y_predSGD = clf.predict(X_test)

In [ ]:
import warnings 
warnings.filterwarnings('ignore') 

results = cross_val_score(clf, X_test, y_test)
print("Accuracy: ", results, '\n')

Accuracy:  [0.95652174 0.65217391 0.56521739 0.90909091 0.90909091] 



In [ ]:
y_predSGD[1:6]

array([1, 1, 1, 0, 0])

In [ ]:
predictions_nominal = [ "M" if x < 0.5 else "B" for x in y_predSGD]
predictions_nominal[1:6]

['B', 'B', 'B', 'M', 'M']

In [ ]:
cfm = confusion_matrix(y_test, y_predSGD)

true_negative = cfm[0][0]
false_positive = cfm[0][1]
false_negative = cfm[1][0]
true_positive = cfm[1][1]

print('Confusion Matrix: \n', cfm, '\n')

print('True Negative:', true_negative)
print('False Positive:', false_positive)
print('False Negative:', false_negative)
print('True Positive:', true_positive)
print('Correct Predictions', 
      round((true_negative + true_positive) / len(predictions_nominal) * 100, 1), '%')

Confusion Matrix: 
 [[20  6]
 [ 1 86]] 

True Negative: 20
False Positive: 6
False Negative: 1
True Positive: 86
Correct Predictions 93.8 %
